=== hmcts/cath-service/libs/list-types/business-and-property-division-rolls-building-daily-cause-list/src/schemas/business-and-property-division-rolls-building-daily-cause-list.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Business and Property Division Rolls Building Daily Cause List",
  "description": "Schema for the 16-section Business and Property Division Rolls Building Daily Cause List",
  "type": "object",
  "required": [
    "appealList",
    "businessList",
    "commercialCourt",
    "financialList",
    "insolvency&CompaniesCourt",
    "ip&EnterpriseCourt",
    "intellectualPropertyList",
    "londonCircuitCommercialCourt",
    "patentsCourt",
    "property,Trusts&ProbateList",
    "technology&ConstructionCourt",
    "admiraltyCourt",
    "companiesWindingUp",
    "competitionList",
    "pensionsList",
    "revenueList"
  ],
  "properties": {
    "appealList": {
      "type": "array",
      "items": {
        "type": "object",
        "required": ["judge", "time", "venue", "type", "caseNumber", "caseName", "additionalInformation"],
        "properties": {
          "judge": {
            "type": "string",
            "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
          },
          "time": {
            "type": "string",
            "pattern": "^\\d{1,2}([:.]\\d{2})?[aApP][mM]\\s*$"
          },
          "venue": {
            "type": "string",
            "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
          },
          "type": {
            "type": "string",
            "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
          },
          "caseNumber": {
            "type": "string",
            "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
          },
          "caseName": {
            "type": "string",
            "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
          },
          "additionalInformation": {
            "type": "string",
            "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
          }
        }
      }
    },
    "businessList": {
      "type": "array",
      "items": {
        "type": "object",
        "required": ["judge", "time", "venue", "type", "caseNumber", "caseName", "additionalInformation"],
        "properties": {
          "judge": {
            "type": "string",
            "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
          },
          "time": {
            "type": "string",
            "pattern": "^\\d{1,2}([:.]\\d{2})?[aApP][mM]\\s*$"
          },
          "venue": {
            "type": "string",
            "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
          },
          "type": {
            "type": "string",
            "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
          },
          "caseNumber": {
            "type": "string",
            "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
          },
          "caseName": {
            "type": "string",
            "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
          },
          "additionalInformation": {
            "type": "string",
            "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
          }
        }
      }
    },
    "commercialCourt": {
      "type": "array",
      "items": {
        "type": "object",
        "required": ["judge", "time", "venue", "type", "caseNumber", "caseName", "additionalInformation"],
        "properties": {
          "judge": {
            "type": "string",
            "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
          },
          "time": {
            "type": "string",
            "pattern": "^\\d{1,2}([:.]\\d{2})?[aApP][mM]\\s*$"
          },
          "venue": {
            "type": "string",
            "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
          },
          "type": {
            "type": "string",
            "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
          },
          "caseNumber": {
            "type": "string",
            "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
          },
          "caseName": {
            "type": "string",
            "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
          },
          "additionalInformation": {
            "type": "string",
            "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
          }
        }
      }
    },
    "financialList": {
      "type": "array",
      "items": {
        "type": "object",
        "required": ["judge", "time", "venue", "type", "caseNumber", "caseName", "additionalInformation"],
        "properties": {
          "judge": {
            "type": "string",
            "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
          },
          "time": {
            "type": "string",
            "pattern": "^\\d{1,2}([:.]\\d{2})?[aApP][mM]\\s*$"
          },
          "venue": {
            "type": "string",
            "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
          },
          "type": {
            "type": "string",
            "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
          },
          "caseNumber": {
            "type": "string",
            "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
          },
          "caseName": {
            "type": "string",
            "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
          },
          "additionalInformation": {
            "type": "string",
            "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
          }
        }
      }
    },
    "insolvency&CompaniesCourt": {
      "type": "array",
      "items": {
        "type": "object",
        "required": ["judge", "time", "venue", "type", "caseNumber", "caseName", "additionalInformation"],
        "properties": {
          "judge": {
            "type": "string",
            "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
          },
          "time": {
            "type": "string",
            "pattern": "^\\d{1,2}([:.]\\d{2})?[aApP][mM]\\s*$"
          },
          "venue": {
            "type": "string",
            "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
          },
          "type": {
            "type": "string",
            "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
          },
          "caseNumber": {
            "type": "string",
            "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
          },
          "caseName": {
            "type": "string",
            "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
          },
          "additionalInformation": {
            "type": "string",
            "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
          }
        }
      }
    },
    "ip&EnterpriseCourt": {
      "type": "array",
      "items": {
        "type": "object",
        "required": ["judge", "time", "venue", "type", "caseNumber", "caseName", "additionalInformation"],
        "properties": {
          "judge": {
            "type": "string",
            "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
          },
          "time": {
            "type": "string",
            "pattern": "^\\d{1,2}([:.]\\d{2})?[aApP][mM]\\s*$"
          },
          "venue": {
            "type": "string",
            "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
          },
          "type": {
            "type": "string",
            "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
          },
          "caseNumber": {
            "type": "string",
            "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
          },
          "caseName": {
            "type": "string",
            "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
          },
          "additionalInformation": {
            "type": "string",
            "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
          }
        }
      }
    },
    "intellectualPropertyList": {
      "type": "array",
      "items": {
        "type": "object",
        "required": ["judge", "time", "venue", "type", "caseNumber", "caseName", "additionalInformation"],
        "properties": {
          "judge": {
            "type": "string",
            "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
          },
          "time": {
            "type": "string",
            "pattern": "^\\d{1,2}([:.]\\d{2})?[aApP][mM]\\s*$"
          },
          "venue": {
            "type": "string",
            "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
          },
          "type": {
            "type": "string",
            "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
          },
          "caseNumber": {
            "type": "string",
            "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
          },
          "caseName": {
            "type": "string",
            "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
          },
          "additionalInformation": {
            "type": "string",
            "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
          }
        }
      }
    },
    "londonCircuitCommercialCourt": {
      "type": "array",
      "items": {
        "type": "object",
        "required": ["judge", "time", "venue", "type", "caseNumber", "caseName", "additionalInformation"],
        "properties": {
          "judge": {
            "type": "string",
            "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
          },
          "time": {
            "type": "string",
            "pattern": "^\\d{1,2}([:.]\\d{2})?[aApP][mM]\\s*$"
          },
          "venue": {
            "type": "string",
            "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
          },
          "type": {
            "type": "string",
            "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
          },
          "caseNumber": {
            "type": "string",
            "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
          },
          "caseName": {
            "type": "string",
            "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
          },
          "additionalInformation": {
            "type": "string",
            "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
          }
        }
      }
    },
    "patentsCourt": {
      "type": "array",
      "items": {
        "type": "object",
        "required": ["judge", "time", "venue", "type", "caseNumber", "caseName", "additionalInformation"],
        "properties": {
          "judge": {
            "type": "string",
            "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
          },
          "time": {
            "type": "string",
            "pattern": "^\\d{1,2}([:.]\\d{2})?[aApP][mM]\\s*$"
          },
          "venue": {
            "type": "string",
            "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
          },
          "type": {
            "type": "string",
            "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
          },
          "caseNumber": {
            "type": "string",
            "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
          },
          "caseName": {
            "type": "string",
            "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
          },
          "additionalInformation": {
            "type": "string",
            "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
          }
        }
      }
    },
    "property,Trusts&ProbateList": {
      "type": "array",
      "items": {
        "type": "object",
        "required": ["judge", "time", "venue", "type", "caseNumber", "caseName", "additionalInformation"],
        "properties": {
          "judge": {
            "type": "string",
            "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
          },
          "time": {
            "type": "string",
            "pattern": "^\\d{1,2}([:.]\\d{2})?[aApP][mM]\\s*$"
          },
          "venue": {
            "type": "string",
            "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
          },
          "type": {
            "type": "string",
            "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
          },
          "caseNumber": {
            "type": "string",
            "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
          },
          "caseName": {
            "type": "string",
            "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
          },
          "additionalInformation": {
            "type": "string",
            "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
          }
        }
      }
    },
    "technology&ConstructionCourt": {
      "type": "array",
      "items": {
        "type": "object",
        "required": ["judge", "time", "venue", "type", "caseNumber", "caseName", "additionalInformation"],
        "properties": {
          "judge": {
            "type": "string",
            "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
          },
          "time": {
            "type": "string",
            "pattern": "^\\d{1,2}([:.]\\d{2})?[aApP][mM]\\s*$"
          },
          "venue": {
            "type": "string",
            "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
          },
          "type": {
            "type": "string",
            "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
          },
          "caseNumber": {
            "type": "string",
            "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
          },
          "caseName": {
            "type": "string",
            "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
          },
          "additionalInformation": {
            "type": "string",
            "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
          }
        }
      }
    },
    "admiraltyCourt": {
      "type": "array",
      "items": {
        "type": "object",
        "required": ["judge", "time", "venue", "type", "caseNumber", "caseName", "additionalInformation"],
        "properties": {
          "judge": {
            "type": "string",
            "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
          },
          "time": {
            "type": "string",
            "pattern": "^\\d{1,2}([:.]\\d{2})?[aApP][mM]\\s*$"
          },
          "venue": {
            "type": "string",
            "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
          },
          "type": {
            "type": "string",
            "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
          },
          "caseNumber": {
            "type": "string",
            "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
          },
          "caseName": {
            "type": "string",
            "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
          },
          "additionalInformation": {
            "type": "string",
            "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
          }
        }
      }
    },
    "companiesWindingUp": {
      "type": "array",
      "items": {
        "type": "object",
        "required": ["judge", "time", "venue", "type", "caseNumber", "caseName", "additionalInformation"],
        "properties": {
          "judge": {
            "type": "string",
            "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
          },
          "time": {
            "type": "string",
            "pattern": "^\\d{1,2}([:.]\\d{2})?[aApP][mM]\\s*$"
          },
          "venue": {
            "type": "string",
            "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
          },
          "type": {
            "type": "string",
            "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
          },
          "caseNumber": {
            "type": "string",
            "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
          },
          "caseName": {
            "type": "string",
            "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
          },
          "additionalInformation": {
            "type": "string",
            "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
          }
        }
      }
    },
    "competitionList": {
      "type": "array",
      "items": {
        "type": "object",
        "required": ["judge", "time", "venue", "type", "caseNumber", "caseName", "additionalInformation"],
        "properties": {
          "judge": {
            "type": "string",
            "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
          },
          "time": {
            "type": "string",
            "pattern": "^\\d{1,2}([:.]\\d{2})?[aApP][mM]\\s*$"
          },
          "venue": {
            "type": "string",
            "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
          },
          "type": {
            "type": "string",
            "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
          },
          "caseNumber": {
            "type": "string",
            "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
          },
          "caseName": {
            "type": "string",
            "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
          },
          "additionalInformation": {
            "type": "string",
            "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
          }
        }
      }
    },
    "pensionsList": {
      "type": "array",
      "items": {
        "type": "object",
        "required": ["judge", "time", "venue", "type", "caseNumber", "caseName", "additionalInformation"],
        "properties": {
          "judge": {
            "type": "string",
            "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
          },
          "time": {
            "type": "string",
            "pattern": "^\\d{1,2}([:.]\\d{2})?[aApP][mM]\\s*$"
          },
          "venue": {
            "type": "string",
            "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
          },
          "type": {
            "type": "string",
            "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
          },
          "caseNumber": {
            "type": "string",
            "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
          },
          "caseName": {
            "type": "string",
            "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
          },
          "additionalInformation": {
            "type": "string",
            "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
          }
        }
      }
    },
    "revenueList": {
      "type": "array",
      "items": {
        "type": "object",
        "required": ["judge", "time", "venue", "type", "caseNumber", "caseName", "additionalInformation"],
        "properties": {
          "judge": {
            "type": "string",
            "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
          },
          "time": {
            "type": "string",
            "pattern": "^\\d{1,2}([:.]\\d{2})?[aApP][mM]\\s*$"
          },
          "venue": {
            "type": "string",
            "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
          },
          "type": {
            "type": "string",
            "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
          },
          "caseNumber": {
            "type": "string",
            "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
          },
          "caseName": {
            "type": "string",
            "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
          },
          "additionalInformation": {
            "type": "string",
            "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
          }
        }
      }
    }
  }
}

=== hmcts/cath-service/e2e-tests/fixtures/list-types/business-and-property-division-rolls-building-daily-cause-list.json
{
  "appealList": [
    {
      "judge": "Mr Justice Smith",
      "time": "10am",
      "venue": "Court 1",
      "type": "Trial",
      "caseNumber": "CR-2026-000123",
      "caseName": "Acme v Widgets",
      "additionalInformation": "Listed for 1 day"
    }
  ],
  "businessList": [
    {
      "judge": "Mr Justice Smith",
      "time": "10am",
      "venue": "Court 1",
      "type": "Trial",
      "caseNumber": "CR-2026-000123",
      "caseName": "Acme v Widgets",
      "additionalInformation": "Listed for 1 day"
    }
  ],
  "commercialCourt": [
    {
      "judge": "Mr Justice Smith",
      "time": "10am",
      "venue": "Court 1",
      "type": "Trial",
      "caseNumber": "CR-2026-000123",
      "caseName": "Acme v Widgets",
      "additionalInformation": "Listed for 1 day"
    }
  ],
  "financialList": [
    {
      "judge": "Mr Justice Smith",
      "time": "10am",
      "venue": "Court 1",
      "type": "Trial",
      "caseNumber": "CR-2026-000123",
      "caseName": "Acme v Widgets",
      "additionalInformation": "Listed for 1 day"
    }
  ],
  "insolvency&CompaniesCourt": [
    {
      "judge": "Mr Justice Smith",
      "time": "10am",
      "venue": "Court 1",
      "type": "Trial",
      "caseNumber": "CR-2026-000123",
      "caseName": "Acme v Widgets",
      "additionalInformation": "Listed for 1 day"
    }
  ],
  "ip&EnterpriseCourt": [
    {
      "judge": "Mr Justice Smith",
      "time": "10am",
      "venue": "Court 1",
      "type": "Trial",
      "caseNumber": "CR-2026-000123",
      "caseName": "Acme v Widgets",
      "additionalInformation": "Listed for 1 day"
    }
  ],
  "intellectualPropertyList": [
    {
      "judge": "Mr Justice Smith",
      "time": "10am",
      "venue": "Court 1",
      "type": "Trial",
      "caseNumber": "CR-2026-000123",
      "caseName": "Acme v Widgets",
      "additionalInformation": "Listed for 1 day"
    }
  ],
  "londonCircuitCommercialCourt": [
    {
      "judge": "Mr Justice Smith",
      "time": "10am",
      "venue": "Court 1",
      "type": "Trial",
      "caseNumber": "CR-2026-000123",
      "caseName": "Acme v Widgets",
      "additionalInformation": "Listed for 1 day"
    }
  ],
  "patentsCourt": [
    {
      "judge": "Mr Justice Smith",
      "time": "10am",
      "venue": "Court 1",
      "type": "Trial",
      "caseNumber": "CR-2026-000123",
      "caseName": "Acme v Widgets",
      "additionalInformation": "Listed for 1 day"
    }
  ],
  "property,Trusts&ProbateList": [
    {
      "judge": "Mr Justice Smith",
      "time": "10am",
      "venue": "Court 1",
      "type": "Trial",
      "caseNumber": "CR-2026-000123",
      "caseName": "Acme v Widgets",
      "additionalInformation": "Listed for 1 day"
    }
  ],
  "technology&ConstructionCourt": [
    {
      "judge": "Mr Justice Smith",
      "time": "10am",
      "venue": "Court 1",
      "type": "Trial",
      "caseNumber": "CR-2026-000123",
      "caseName": "Acme v Widgets",
      "additionalInformation": "Listed for 1 day"
    }
  ],
  "admiraltyCourt": [
    {
      "judge": "Mr Justice Smith",
      "time": "10am",
      "venue": "Court 1",
      "type": "Trial",
      "caseNumber": "CR-2026-000123",
      "caseName": "Acme v Widgets",
      "additionalInformation": "Listed for 1 day"
    }
  ],
  "companiesWindingUp": [
    {
      "judge": "Mr Justice Smith",
      "time": "10am",
      "venue": "Court 1",
      "type": "Trial",
      "caseNumber": "CR-2026-000123",
      "caseName": "Acme v Widgets",
      "additionalInformation": "Listed for 1 day"
    }
  ],
  "competitionList": [
    {
      "judge": "Mr Justice Smith",
      "time": "10am",
      "venue": "Court 1",
      "type": "Trial",
      "caseNumber": "CR-2026-000123",
      "caseName": "Acme v Widgets",
      "additionalInformation": "Listed for 1 day"
    }
  ],
  "pensionsList": [
    {
      "judge": "Mr Justice Smith",
      "time": "10am",
      "venue": "Court 1",
      "type": "Trial",
      "caseNumber": "CR-2026-000123",
      "caseName": "Acme v Widgets",
      "additionalInformation": "Listed for 1 day"
    }
  ],
  "revenueList": [
    {
      "judge": "Mr Justice Smith",
      "time": "10am",
      "venue": "Court 1",
      "type": "Trial",
      "caseNumber": "CR-2026-000123",
      "caseName": "Acme v Widgets",
      "additionalInformation": "Listed for 1 day"
    }
  ]
}
